version: '3.7'

services:
  web:
    build:
      context: .
    command: [ "python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload" ]
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENV=dev
      - DB_URL=mongodb://mongo:27017
    depends_on:
      - redis
      - mongo
    restart: on-failure

  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
    restart: on-failure

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    restart: on-failure
